language: scala
sudo: false
scala:
  - 2.12.12
  - 2.13.3
before_script:
  - mkdir lib
  - curl -L -o AthenaJDBC41_2.0.7.jar https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.7/AthenaJDBC41_2.0.7.jar
  - mv AthenaJDBC41_2.0.7.jar lib/
